### ISSUE TITLE
Budgets for Justice for Assam

### ISSUE THREAD

**Issue by Abhi2102** [justicehub-in/budget-for-justice#78]
## Is your feature request related to a problem? Please describe.
General
- [ ] Mention of 2022-23 missing on website
- [x] Add meta tags
- [x] Add ga snippet
- [ ] Add to sitemap
- [x] Color scheme. font and topography as per design

State Page

- [x] change grant link of upper cards
- [x] update card values
- [x] #79
- [x] change highlight section on grant click
- [x] link open guide book
- [x] add more button in resources and link to res page
- [x] change resource and their links in res section 

Resource Page

- [x] change res text and links

Grants page

- [x]  remove grant number from title name and add below
- [x] update middle section
- [x] remove load more section from bottom
- [x] build search for scheme
- [x] fix home breadcrumb

Scheme Page

- [x] Fix tab title , its coming undefined
- [x] Fix header , header section with search functionality missing currently
- [x] change data source
- [x] fix download chart and csv 
- [x] fix download data package
- [x] change other budget datasets text 
- [x] other budget datasets section is emtpy
- [x] check share functionality
- [x] Populate header cards with actual value

**Comment by apoorv74** [comment]
Pending issues have been added to #89
